name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: npm install
        run: npm install
      #- name: Test Error
      #if: ${{ failure() }}
      #uses: rjstone/discord-webhook-notify@v1
      #with:
      #severity: error
      #details: Build failed
      #webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      #- name: lint
      #run: npm run eslint
      #- name: Run tests 🧪
      # https://github.com/cypress-io/github-action
      #uses: cypress-io/github-action@v2
      #if: ${{ false }}
      #with:
      #start: npm start
      #wait-on: 'http://localhost:3000'
      - name: Deploy to heroku
        #if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'iatf-bot' #Must be unique in Heroku
          heroku_email: 'sangalesbenes@uoc.edu'
          healthcheck: 'https://iatf-bot.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
          #appdir: 'src'
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Info
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: A new version of IATF-BOT deployed.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
